FROM debian:jessie
MAINTAINER Toomore Chiang <toomore0929@gmail.com>

ADD ./twsereport /usr/local/bin/
ADD ./twsecache /usr/local/bin/
ADD ./realtime /usr/local/bin/
ADD ./tradingdays_server /usr/local/bin/
